package com.util;

import javax.mail.*;
import javax.mail.internet.*;
import java.util.Properties;

public class Email {

    private String emailAddressTo = new String();
    private String msgSubject = new String();
    private String msgText = new String();

    final String USER_NAME = "deanslist.2014@gmail.com";   //User name of the Goole(gmail) account
    final String PASSSWORD = "Sherm310590";  //Password of the Goole(gmail) account
    final String FROM_ADDRESS = "deanslist.2014@gmail.com";  //From addresss



    public Email(String toAddress) {
        this.emailAddressTo = toAddress;
    }

    public void signupEmail(String link) {
        this.msgSubject = msgSubject;
        sendEmailMessage(link, "verification_email");

    }

    private void sendEmailMessage(String link, String emailType) {

        //Create email sending properties
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");

        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(USER_NAME, PASSSWORD);
                    }
                });

        try {
            if (emailType.equals("verification_email")) {
                msgText = getVerifyTemplate(link);
            }
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(FROM_ADDRESS)); //Set from address of the email
            message.setContent(msgText, "text/html"); //set content type of the email

            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(emailAddressTo)); //Set email recipient

            message.setSubject(msgSubject); //Set email message subject
            Transport.send(message); //Send email message

            System.out.println("sent email successfully!");

        } catch (MessagingException e) {
            throw new RuntimeException(e);
        }
    }

    public void setEmailAddressTo(String emailAddressTo) {
        this.emailAddressTo = emailAddressTo;
    }

    public void setSubject(String subject) {
        this.msgSubject = subject;
    }

    public void setMessageText(String msgText) {
        this.msgText = msgText;
    }

    public String getVerifyTemplate(String link) {
        String template = "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\">\n"
                + "<head>\n"
                + "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n"
                + "<title>DeansList | Email Verification<br></title>\n"
                + "<meta name=\"viewport\" content=\"width=device-width\"/>\n"
                + "<style type=\"text/css\">\n"
                + " #outlook a { \n"
                + "            padding:0; \n"
                + "            } \n"
                + "            body{ \n"
                + "            width:100% !important; \n"
                + "            min-width: 100%;\n"
                + "            -webkit-text-size-adjust:100%; \n"
                + "            -ms-text-size-adjust:100%; \n"
                + "            margin:0; \n"
                + "            padding:0;\n"
                + "            }\n"
                + "            .ExternalClass { \n"
                + "            width:100%;\n"
                + "            } \n"
                + "            .ExternalClass, \n"
                + "            .ExternalClass p, \n"
                + "            .ExternalClass span, \n"
                + "            .ExternalClass font, \n"
                + "            .ExternalClass td, \n"
                + "            .ExternalClass div { \n"
                + "            line-height: 100%; \n"
                + "            } \n"
                + "            #backgroundTable { \n"
                + "            margin:0; \n"
                + "            padding:0; \n"
                + "            width:100% !important; \n"
                + "            line-height: 100% !important; \n"
                + "            }\n"
                + "            img { \n"
                + "            outline:none; \n"
                + "            text-decoration:none; \n"
                + "            -ms-interpolation-mode1: bicubic;\n"
                + "            width: auto;\n"
                + "            max-width: 100%; \n"
                + "            float: left; \n"
                + "            clear: both; \n"
                + "            display: block;\n"
                + "            }\n"
                + "            center {\n"
                + "            width: 100%;\n"
                + "            min-width: 580px;\n"
                + "            }\n"
                + "            a img { \n"
                + "            border: none;\n"
                + "            }\n"
                + "            p {\n"
                + "            margin: 0 0 0 10px;\n"
                + "            }\n"
                + "            table {\n"
                + "            border-spacing: 0;\n"
                + "            border-collapse: collapse;\n"
                + "            }\n"
                + "            td { \n"
                + "            word-break: break-word;\n"
                + "            -webkit-hyphens: auto;\n"
                + "            -moz-hyphens: auto;\n"
                + "            hyphens: auto;\n"
                + "            border-collapse: collapse !important; \n"
                + "            }\n"
                + "            table, tr, td {\n"
                + "            padding: 0;\n"
                + "            vertical-align: top;\n"
                + "            text-align: left;\n"
                + "            }\n"
                + "            hr {\n"
                + "            color: #d9d9d9; \n"
                + "            background-color: #d9d9d9; \n"
                + "            height: 1px; \n"
                + "            border: none;\n"
                + "            }\n"
                + "            /* Responsive Grid */\n"
                + "            table.body {\n"
                + "            height: 100%;\n"
                + "            width: 100%;\n"
                + "            }\n"
                + "            table.container {\n"
                + "            width: 580px;\n"
                + "            margin: 0 auto;\n"
                + "            text-align: inherit;\n"
                + "            }\n"
                + "            table.row { \n"
                + "            padding: 0px; \n"
                + "            width: 100%;\n"
                + "            position: relative;\n"
                + "            }\n"
                + "            table.container table.row {\n"
                + "            display: block;\n"
                + "            }\n"
                + "            td.wrapper {\n"
                + "            padding: 10px 20px 0px 0px;\n"
                + "            position: relative;\n"
                + "            }\n"
                + "            table.columns,\n"
                + "            table.column {\n"
                + "            margin: 0 auto;\n"
                + "            }\n"
                + "            table.columns td,\n"
                + "            table.column td {\n"
                + "            padding: 0px 0px 10px; \n"
                + "            }\n"
                + "            table.columns td.sub-columns,\n"
                + "            table.column td.sub-columns,\n"
                + "            table.columns td.sub-column,\n"
                + "            table.column td.sub-column {\n"
                + "            padding-right: 10px;\n"
                + "            }\n"
                + "            td.sub-column, td.sub-columns {\n"
                + "            min-width: 0px;\n"
                + "            }\n"
                + "            table.row td.last,\n"
                + "            table.container td.last {\n"
                + "            padding-right: 0px;\n"
                + "            }\n"
                + "            table.one { width: 30px; }\n"
                + "            table.two { width: 80px; }\n"
                + "            table.three { width: 130px; }\n"
                + "            table.four { width: 180px; }\n"
                + "            table.five { width: 230px; }\n"
                + "            table.six { width: 280px; }\n"
                + "            table.seven { width: 330px; }\n"
                + "            table.eight { width: 380px; }\n"
                + "            table.nine { width: 430px; }\n"
                + "            table.ten { width: 480px; }\n"
                + "            table.eleven { width: 530px; }\n"
                + "            table.twelve { width: 580px; }\n"
                + "            table.one center { min-width: 30px; }\n"
                + "            table.two center { min-width: 80px; }\n"
                + "            table.three center { min-width: 130px; }\n"
                + "            table.four center { min-width: 180px; }\n"
                + "            table.five center { min-width: 230px; }\n"
                + "            table.six center { min-width: 280px; }\n"
                + "            table.seven center { min-width: 330px; }\n"
                + "            table.eight center { min-width: 380px; }\n"
                + "            table.nine center { min-width: 430px; }\n"
                + "            table.ten center { min-width: 480px; }\n"
                + "            table.eleven center { min-width: 530px; }\n"
                + "            table.twelve center { min-width: 580px; }\n"
                + "            table.one .panel center { min-width: 10px; }\n"
                + "            table.two .panel center { min-width: 60px; }\n"
                + "            table.three .panel center { min-width: 110px; }\n"
                + "            table.four .panel center { min-width: 160px; }\n"
                + "            table.five .panel center { min-width: 210px; }\n"
                + "            table.six .panel center { min-width: 260px; }\n"
                + "            table.seven .panel center { min-width: 310px; }\n"
                + "            table.eight .panel center { min-width: 360px; }\n"
                + "            table.nine .panel center { min-width: 410px; }\n"
                + "            table.ten .panel center { min-width: 460px; }\n"
                + "            table.eleven .panel center { min-width: 510px; }\n"
                + "            table.twelve .panel center { min-width: 560px; }\n"
                + "            .body .columns td.one,\n"
                + "            .body .column td.one { width: 8.333333%; }\n"
                + "            .body .columns td.two,\n"
                + "            .body .column td.two { width: 16.666666%; }\n"
                + "            .body .columns td.three,\n"
                + "            .body .column td.three { width: 25%; }\n"
                + "            .body .columns td.four,\n"
                + "            .body .column td.four { width: 33.333333%; }\n"
                + "            .body .columns td.five,\n"
                + "            .body .column td.five { width: 41.666666%; }\n"
                + "            .body .columns td.six,\n"
                + "            .body .column td.six { width: 50%; }\n"
                + "            .body .columns td.seven,\n"
                + "            .body .column td.seven { width: 58.333333%; }\n"
                + "            .body .columns td.eight,\n"
                + "            .body .column td.eight { width: 66.666666%; }\n"
                + "            .body .columns td.nine,\n"
                + "            .body .column td.nine { width: 75%; }\n"
                + "            .body .columns td.ten,\n"
                + "            .body .column td.ten { width: 83.333333%; }\n"
                + "            .body .columns td.eleven,\n"
                + "            .body .column td.eleven { width: 91.666666%; }\n"
                + "            .body .columns td.twelve,\n"
                + "            .body .column td.twelve { width: 100%; }\n"
                + "            td.offset-by-one { padding-left: 50px; }\n"
                + "            td.offset-by-two { padding-left: 100px; }\n"
                + "            td.offset-by-three { padding-left: 150px; }\n"
                + "            td.offset-by-four { padding-left: 200px; }\n"
                + "            td.offset-by-five { padding-left: 250px; }\n"
                + "            td.offset-by-six { padding-left: 300px; }\n"
                + "            td.offset-by-seven { padding-left: 350px; }\n"
                + "            td.offset-by-eight { padding-left: 400px; }\n"
                + "            td.offset-by-nine { padding-left: 450px; }\n"
                + "            td.offset-by-ten { padding-left: 500px; }\n"
                + "            td.offset-by-eleven { padding-left: 550px; }\n"
                + "            td.expander {\n"
                + "            visibility: hidden;\n"
                + "            width: 0px;\n"
                + "            padding: 0 !important;\n"
                + "            }\n"
                + "            table.columns .text-pad,\n"
                + "            table.column .text-pad {\n"
                + "            padding-left: 10px;\n"
                + "            padding-right: 10px;\n"
                + "            }\n"
                + "            table.columns .left-text-pad,\n"
                + "            table.columns .text-pad-left,\n"
                + "            table.column .left-text-pad,\n"
                + "            table.column .text-pad-left {\n"
                + "            padding-left: 10px;\n"
                + "            }\n"
                + "            table.columns .right-text-pad,\n"
                + "            table.columns .text-pad-right,\n"
                + "            table.column .right-text-pad,\n"
                + "            table.column .text-pad-right {\n"
                + "            padding-right: 10px;\n"
                + "            }\n"
                + "            /* Block Grid */\n"
                + "            .block-grid {\n"
                + "            width: 100%;\n"
                + "            max-width: 580px;\n"
                + "            }\n"
                + "            .block-grid td {\n"
                + "            display: inline-block;\n"
                + "            padding:10px;\n"
                + "            }\n"
                + "            .two-up td {\n"
                + "            width:270px;\n"
                + "            }\n"
                + "            .three-up td {\n"
                + "            width:173px;\n"
                + "            }\n"
                + "            .four-up td {\n"
                + "            width:125px;\n"
                + "            }\n"
                + "            .five-up td {\n"
                + "            width:96px;\n"
                + "            }\n"
                + "            .six-up td {\n"
                + "            width:76px;\n"
                + "            }\n"
                + "            .seven-up td {\n"
                + "            width:62px;\n"
                + "            }\n"
                + "            .eight-up td {\n"
                + "            width:52px;\n"
                + "            }\n"
                + "            /* Alignment & Visibility Classes */\n"
                + "            table.center, td.center {\n"
                + "            text-align: center;\n"
                + "            }\n"
                + "            h1.center,\n"
                + "            h2.center,\n"
                + "            h3.center,\n"
                + "            h4.center,\n"
                + "            h5.center,\n"
                + "            h6.center {\n"
                + "            text-align: center;\n"
                + "            }\n"
                + "            span.center {\n"
                + "            display: block;\n"
                + "            width: 100%;\n"
                + "            text-align: center;\n"
                + "            }\n"
                + "            img.center {\n"
                + "            margin: 0 auto;\n"
                + "            float: none;\n"
                + "            }\n"
                + "            .show-for-small,\n"
                + "            .hide-for-desktop {\n"
                + "            display: none;\n"
                + "            }\n"
                + "            /* Typography */\n"
                + "            body, table.body, h1, h2, h3, h4, h5, h6, p, td { \n"
                + "            color: #222222;\n"
                + "            font-family: \"Helvetica\", \"Arial\", sans-serif; \n"
                + "            font-weight: normal; \n"
                + "            padding:0; \n"
                + "            margin: 0;\n"
                + "            text-align: left; \n"
                + "            line-height: 1.3;\n"
                + "            }\n"
                + "            h1, h2, h3, h4, h5, h6 {\n"
                + "            word-break: normal;\n"
                + "            }\n"
                + "            h1 {font-size: 40px;}\n"
                + "            h2 {font-size: 36px;}\n"
                + "            h3 {font-size: 32px;}\n"
                + "            h4 {font-size: 28px;}\n"
                + "            h5 {font-size: 24px;}\n"
                + "            h6 {font-size: 20px;}\n"
                + "            body, table.body, p, td {font-size: 14px;line-height:19px;}\n"
                + "            p.lead, p.lede, p.leed {\n"
                + "            font-size: 18px;\n"
                + "            line-height:21px;\n"
                + "            }\n"
                + "            p { \n"
                + "            margin-bottom: 10px;\n"
                + "            }\n"
                + "            small {\n"
                + "            font-size: 10px;\n"
                + "            }\n"
                + "            a {\n"
                + "            color: #2ba6cb; \n"
                + "            text-decoration: none;\n"
                + "            }\n"
                + "            a:hover { \n"
                + "            color: #2795b6 !important;\n"
                + "            }\n"
                + "            a:active { \n"
                + "            color: #2795b6 !important;\n"
                + "            }\n"
                + "            a:visited { \n"
                + "            color: #2ba6cb !important;\n"
                + "            }\n"
                + "            h1 a, \n"
                + "            h2 a, \n"
                + "            h3 a, \n"
                + "            h4 a, \n"
                + "            h5 a, \n"
                + "            h6 a {\n"
                + "            color: #2ba6cb;\n"
                + "            }\n"
                + "            h1 a:active, \n"
                + "            h2 a:active,  \n"
                + "            h3 a:active, \n"
                + "            h4 a:active, \n"
                + "            h5 a:active, \n"
                + "            h6 a:active { \n"
                + "            color: #2ba6cb !important; \n"
                + "            } \n"
                + "            h1 a:visited, \n"
                + "            h2 a:visited,  \n"
                + "            h3 a:visited, \n"
                + "            h4 a:visited, \n"
                + "            h5 a:visited, \n"
                + "            h6 a:visited { \n"
                + "            color: #2ba6cb !important; \n"
                + "            } \n"
                + "            /* Panels */\n"
                + "            .panel {\n"
                + "            background: #f2f2f2;\n"
                + "            border: 1px solid #d9d9d9;\n"
                + "            padding: 10px !important;\n"
                + "            }\n"
                + "            .sub-grid table {\n"
                + "            width: 100%;\n"
                + "            }\n"
                + "            .sub-grid td.sub-columns {\n"
                + "            padding-bottom: 0;\n"
                + "            }\n"
                + "            /* Buttons */\n"
                + "            table.button,\n"
                + "            table.tiny-button,\n"
                + "            table.small-button,\n"
                + "            table.medium-button,\n"
                + "            table.large-button {\n"
                + "            width: 100%;\n"
                + "            overflow: hidden;\n"
                + "            }\n"
                + "            table.button td,\n"
                + "            table.tiny-button td,\n"
                + "            table.small-button td,\n"
                + "            table.medium-button td,\n"
                + "            table.large-button td {\n"
                + "            display: block;\n"
                + "            width: auto !important;\n"
                + "            text-align: center;\n"
                + "            background: #2ba6cb;\n"
                + "            border: 1px solid #2284a1;\n"
                + "            color: #ffffff;\n"
                + "            padding: 8px 0;\n"
                + "            }\n"
                + "            table.tiny-button td {\n"
                + "            padding: 5px 0 4px;\n"
                + "            }\n"
                + "            table.small-button td {\n"
                + "            padding: 8px 0 7px;\n"
                + "            }\n"
                + "            table.medium-button td {\n"
                + "            padding: 12px 0 10px;\n"
                + "            }\n"
                + "            table.large-button td {\n"
                + "            padding: 21px 0 18px;\n"
                + "            }\n"
                + "            table.button td a,\n"
                + "            table.tiny-button td a,\n"
                + "            table.small-button td a,\n"
                + "            table.medium-button td a,\n"
                + "            table.large-button td a {\n"
                + "            font-weight: bold;\n"
                + "            text-decoration: none;\n"
                + "            font-family: Helvetica, Arial, sans-serif;\n"
                + "            color: #ffffff;\n"
                + "            font-size: 16px;\n"
                + "            }\n"
                + "            table.tiny-button td a {\n"
                + "            font-size: 12px;\n"
                + "            font-weight: normal;\n"
                + "            }\n"
                + "            table.small-button td a {\n"
                + "            font-size: 16px;\n"
                + "            }\n"
                + "            table.medium-button td a {\n"
                + "            font-size: 20px;\n"
                + "            }\n"
                + "            table.large-button td a {\n"
                + "            font-size: 24px;\n"
                + "            }\n"
                + "            table.button:hover td,\n"
                + "            table.button:visited td,\n"
                + "            table.button:active td {\n"
                + "            background: #2795b6 !important;\n"
                + "            }\n"
                + "            table.button:hover td a,\n"
                + "            table.button:visited td a,\n"
                + "            table.button:active td a {\n"
                + "            color: #fff !important;\n"
                + "            }\n"
                + "            table.button:hover td,\n"
                + "            table.tiny-button:hover td,\n"
                + "            table.small-button:hover td,\n"
                + "            table.medium-button:hover td,\n"
                + "            table.large-button:hover td {\n"
                + "            background: #2795b6 !important;\n"
                + "            }\n"
                + "            table.button:hover td a,\n"
                + "            table.button:active td a,\n"
                + "            table.button td a:visited,\n"
                + "            table.tiny-button:hover td a,\n"
                + "            table.tiny-button:active td a,\n"
                + "            table.tiny-button td a:visited,\n"
                + "            table.small-button:hover td a,\n"
                + "            table.small-button:active td a,\n"
                + "            table.small-button td a:visited,\n"
                + "            table.medium-button:hover td a,\n"
                + "            table.medium-button:active td a,\n"
                + "            table.medium-button td a:visited,\n"
                + "            table.large-button:hover td a,\n"
                + "            table.large-button:active td a,\n"
                + "            table.large-button td a:visited {\n"
                + "            color: #ffffff !important; \n"
                + "            }\n"
                + "            table.secondary td {\n"
                + "            background: #e9e9e9;\n"
                + "            border-color: #d0d0d0;\n"
                + "            color: #555;\n"
                + "            }\n"
                + "            table.secondary td a {\n"
                + "            color: #555;\n"
                + "            }\n"
                + "            table.secondary:hover td {\n"
                + "            background: #d0d0d0 !important;\n"
                + "            color: #555;\n"
                + "            }\n"
                + "            table.secondary:hover td a,\n"
                + "            table.secondary td a:visited,\n"
                + "            table.secondary:active td a {\n"
                + "            color: #555 !important;\n"
                + "            }\n"
                + "            table.success td {\n"
                + "            background: #5da423;\n"
                + "            border-color: #457a1a;\n"
                + "            }\n"
                + "            table.success:hover td {\n"
                + "            background: #457a1a !important;\n"
                + "            }\n"
                + "            table.alert td {\n"
                + "            background: #c60f13;\n"
                + "            border-color: #970b0e;\n"
                + "            }\n"
                + "            table.alert:hover td {\n"
                + "            background: #970b0e !important;\n"
                + "            }\n"
                + "            table.radius td {\n"
                + "            -webkit-border-radius: 3px;\n"
                + "            -moz-border-radius: 3px;\n"
                + "            border-radius: 3px;\n"
                + "            }\n"
                + "            table.round td {\n"
                + "            -webkit-border-radius: 500px;\n"
                + "            -moz-border-radius: 500px;\n"
                + "            border-radius: 500px;\n"
                + "            }\n"
                + "            /* Outlook First */\n"
                + "            body.outlook p {\n"
                + "            display: inline !important;\n"
                + "            }\n"
                + "            /*  Media Queries */\n"
                + "            @media only screen and (max-width: 600px) {\n"
                + "            table[class=\"body\"] img {\n"
                + "            width: auto !important;\n"
                + "            height: auto !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] center {\n"
                + "            min-width: 0 !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .container {\n"
                + "            width: 95% !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .row {\n"
                + "            width: 100% !important;\n"
                + "            display: block !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .wrapper {\n"
                + "            display: block !important;\n"
                + "            padding-right: 0 !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .columns,\n"
                + "            table[class=\"body\"] .column {\n"
                + "            table-layout: fixed !important;\n"
                + "            float: none !important;\n"
                + "            width: 100% !important;\n"
                + "            padding-right: 0px !important;\n"
                + "            padding-left: 0px !important;\n"
                + "            display: block !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .wrapper.first .columns,\n"
                + "            table[class=\"body\"] .wrapper.first .column {\n"
                + "            display: table !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] table.columns td,\n"
                + "            table[class=\"body\"] table.column td {\n"
                + "            width: 100% !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .columns td.one,\n"
                + "            table[class=\"body\"] .column td.one { width: 8.333333% !important; }\n"
                + "            table[class=\"body\"] .columns td.two,\n"
                + "            table[class=\"body\"] .column td.two { width: 16.666666% !important; }\n"
                + "            table[class=\"body\"] .columns td.three,\n"
                + "            table[class=\"body\"] .column td.three { width: 25% !important; }\n"
                + "            table[class=\"body\"] .columns td.four,\n"
                + "            table[class=\"body\"] .column td.four { width: 33.333333% !important; }\n"
                + "            table[class=\"body\"] .columns td.five,\n"
                + "            table[class=\"body\"] .column td.five { width: 41.666666% !important; }\n"
                + "            table[class=\"body\"] .columns td.six,\n"
                + "            table[class=\"body\"] .column td.six { width: 50% !important; }\n"
                + "            table[class=\"body\"] .columns td.seven,\n"
                + "            table[class=\"body\"] .column td.seven { width: 58.333333% !important; }\n"
                + "            table[class=\"body\"] .columns td.eight,\n"
                + "            table[class=\"body\"] .column td.eight { width: 66.666666% !important; }\n"
                + "            table[class=\"body\"] .columns td.nine,\n"
                + "            table[class=\"body\"] .column td.nine { width: 75% !important; }\n"
                + "            table[class=\"body\"] .columns td.ten,\n"
                + "            table[class=\"body\"] .column td.ten { width: 83.333333% !important; }\n"
                + "            table[class=\"body\"] .columns td.eleven,\n"
                + "            table[class=\"body\"] .column td.eleven { width: 91.666666% !important; }\n"
                + "            table[class=\"body\"] .columns td.twelve,\n"
                + "            table[class=\"body\"] .column td.twelve { width: 100% !important; }\n"
                + "            table[class=\"body\"] td.offset-by-one,\n"
                + "            table[class=\"body\"] td.offset-by-two,\n"
                + "            table[class=\"body\"] td.offset-by-three,\n"
                + "            table[class=\"body\"] td.offset-by-four,\n"
                + "            table[class=\"body\"] td.offset-by-five,\n"
                + "            table[class=\"body\"] td.offset-by-six,\n"
                + "            table[class=\"body\"] td.offset-by-seven,\n"
                + "            table[class=\"body\"] td.offset-by-eight,\n"
                + "            table[class=\"body\"] td.offset-by-nine,\n"
                + "            table[class=\"body\"] td.offset-by-ten,\n"
                + "            table[class=\"body\"] td.offset-by-eleven {\n"
                + "            padding-left: 0 !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] table.columns td.expander {\n"
                + "            width: 1px !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .right-text-pad,\n"
                + "            table[class=\"body\"] .text-pad-right {\n"
                + "            padding-left: 10px !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .left-text-pad,\n"
                + "            table[class=\"body\"] .text-pad-left {\n"
                + "            padding-right: 10px !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .hide-for-small,\n"
                + "            table[class=\"body\"] .show-for-desktop {\n"
                + "            display: none !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] .show-for-small,\n"
                + "            table[class=\"body\"] .hide-for-desktop {\n"
                + "            display: inherit !important;\n"
                + "            }\n"
                + "            }       \n"
                + "           \n"
                + "</style>\n"
                + "<style>\n"
                + "            /**************************************************************\n"
                + "            * Custom Styles *\n"
                + "            ***************************************************************/\n"
                + "            /***\n"
                + "            Reset & Typography\n"
                + "            ***/\n"
                + "            body {\n"
                + "            direction: ltr;\n"
                + "            background: #f6f8f1;\n"
                + "            }   \n"
                + "            a:hover {\n"
                + "            text-decoration: underline;\n"
                + "            }\n"
                + "            h1 {font-size: 34px;}\n"
                + "            h2 {font-size: 30px;}\n"
                + "            h3 {font-size: 26px;}\n"
                + "            h4 {font-size: 22px;}\n"
                + "            h5 {font-size: 18px;}\n"
                + "            h6 {font-size: 16px;}\n"
                + "            h4, h3, h2, h1 {\n"
                + "            display: block;\n"
                + "            margin: 5px 0 15px 0;\n"
                + "            }\n"
                + "            h7, h6, h5 {\n"
                + "            display: block;\n"
                + "            margin: 5px 0 5px 0 !important;\n"
                + "            }\n"
                + "            /***\n"
                + "            Buttons\n"
                + "            ***/\n"
                + "            .btn td {\n"
                + "            background: #e5e5e5 !important;\n"
                + "            border: 0;\n"
                + "            font-family: \"Segoe UI\", Helvetica, Arial, sans-serif;\n"
                + "            font-size: 14px;  \n"
                + "            padding: 7px 14px !important;\n"
                + "            color: #333333 !important;\n"
                + "            text-align: center;\n"
                + "            vertical-align: middle;\n"
                + "            }\n"
                + "            .btn td a {\n"
                + "            display: block;\n"
                + "            color: #fff;\n"
                + "            }\n"
                + "            .btn td a:hover,\n"
                + "            .btn td a:focus,\n"
                + "            .btn td a:active {\n"
                + "            color: #fff !important;\n"
                + "            text-decoration: none;\n"
                + "            }\n"
                + "            .btn td:hover, \n"
                + "            .btn td:focus, \n"
                + "            .btn td:active {  \n"
                + "            background: #d8d8d8 !important;\n"
                + "            }\n"
                + "            /*  Yellow */\n"
                + "            .btn.yellow td {\n"
                + "            background: #ffb848 !important;\n"
                + "            }\n"
                + "            .btn.yellow td:hover, \n"
                + "            .btn.yellow td:focus, \n"
                + "            .btn.yellow td:active { \n"
                + "            background: #eca22e !important;\n"
                + "            }\n"
                + "            .btn.red td{\n"
                + "            background: #d84a38 !important;\n"
                + "            }\n"
                + "            .btn.red td:hover, \n"
                + "            .btn.red td:focus, \n"
                + "            .btn.red td:active {    \n"
                + "            background: #bb2413 !important;\n"
                + "            }\n"
                + "            .btn.green td {\n"
                + "            background: #35aa47 !important;\n"
                + "            }\n"
                + "            .btn.green td:hover, \n"
                + "            .btn.green td:focus, \n"
                + "            .btn.green td:active { \n"
                + "            background: #1d943b !important;\n"
                + "            }\n"
                + "            /*  Blue */\n"
                + "            .btn.blue td {\n"
                + "            background: #4d90fe !important;\n"
                + "            }\n"
                + "            .btn.blue td:hover, \n"
                + "            .btn.blue td:focus, \n"
                + "            .btn.blue td:active {  \n"
                + "            background: #0362fd !important;\n"
                + "            }\n"
                + "            .template-label {\n"
                + "            color: #ffffff;\n"
                + "            font-weight: bold;\n"
                + "            font-size: 11px;\n"
                + "            }\n"
                + "            /***\n"
                + "            Note Panels\n"
                + "            ***/\n"
                + "            .note .panel {\n"
                + "            padding: 10px !important;\n"
                + "            background: #ECF8FF;\n"
                + "            border: 0;\n"
                + "            }\n"
                + "            /***\n"
                + "            Header\n"
                + "            ***/\n"
                + "            .page-header {\n"
                + "            width: 100%;\n"
                + "            background: #1f1f1f;\n"
                + "            }\n"
                + "            /***\n"
                + "            Social Icons\n"
                + "            ***/\n"
                + "            .social-icons {\n"
                + "            float: right;\n"
                + "            }\n"
                + "            .social-icons td {\n"
                + "            padding: 0 2px !important;\n"
                + "            width: auto !important;\n"
                + "            }\n"
                + "            .social-icons td:last-child {\n"
                + "            padding-right: 0 !important;\n"
                + "            }\n"
                + "            .social-icons td img {\n"
                + "            max-width: none !important; \n"
                + "            }\n"
                + "            /***\n"
                + "            Content\n"
                + "            ***/\n"
                + "            table.container.content > tbody > tr > td{\n"
                + "            background: #fff;  \n"
                + "            padding: 15px !important;\n"
                + "            }\n"
                + "            /***\n"
                + "            Footer\n"
                + "            ***/\n"
                + "            .page-footer  {\n"
                + "            width: 100%;\n"
                + "            background: #2f2f2f;\n"
                + "            }\n"
                + "            .page-footer td {\n"
                + "            vertical-align: middle;\n"
                + "            color: #fff;\n"
                + "            }\n"
                + "            /***\n"
                + "            Content devider\n"
                + "            ***/\n"
                + "            .devider {\n"
                + "            border-bottom: 1px solid #eee;\n"
                + "            margin: 15px -15px;\n"
                + "            display: block;\n"
                + "            }\n"
                + "            /***\n"
                + "            Media Item\n"
                + "            ***/\n"
                + "            .media-item img {\n"
                + "            display: block !important;\n"
                + "            float: none;\n"
                + "            margin-bottom: 10px;\n"
                + "            }\n"
                + "            .vertical-middle {\n"
                + "            padding-top: 0;\n"
                + "            padding-bottom: 0;\n"
                + "            vertical-align: middle;\n"
                + "            }\n"
                + "            /***\n"
                + "            Utils\n"
                + "            ***/\n"
                + "            .align-reverse {\n"
                + "            text-align: right;\n"
                + "            }\n"
                + "            .border {\n"
                + "            border: 1px solid red;\n"
                + "            }\n"
                + "            .hidden-mobile {\n"
                + "            display: block;\n"
                + "            }\n"
                + "            .visible-mobile {\n"
                + "            display: none;\n"
                + "            }\n"
                + "            @media only screen and (max-width: 600px) {\n"
                + "            /***\n"
                + "            Reset & Typography\n"
                + "            ***/\n"
                + "            body {\n"
                + "            background: #fff;  \n"
                + "            }\n"
                + "            h1 {font-size: 30px;}\n"
                + "            h2 {font-size: 26px;}\n"
                + "            h3 {font-size: 22px;}\n"
                + "            h4 {font-size: 20px;}\n"
                + "            h5 {font-size: 16px;}\n"
                + "            h6 {font-size: 14px;}\n"
                + "            /***\n"
                + "            Content\n"
                + "            ***/\n"
                + "            table.container.content > tbody > tr > td{\n"
                + "            padding: 0px !important;\n"
                + "            }\n"
                + "            table[class=\"body\"] table.columns .social-icons td {\n"
                + "            width: auto !important;\n"
                + "            }\n"
                + "            /***\n"
                + "            Header\n"
                + "            ***/\n"
                + "            .header {\n"
                + "            padding: 10px !important;\n"
                + "            }\n"
                + "            /***\n"
                + "            Content devider\n"
                + "            ***/\n"
                + "            .devider {\n"
                + "            margin: 15px 0;\n"
                + "            }\n"
                + "            /***\n"
                + "            Media Item\n"
                + "            ***/\n"
                + "            .media-item {\n"
                + "            border-bottom: 1px solid #eee;\n"
                + "            padding: 15px 0 !important;\n"
                + "            }\n"
                + "            /***\n"
                + "            Media Item\n"
                + "            ***/\n"
                + "            .hidden-mobile {\n"
                + "            display: none;\n"
                + "            }\n"
                + "            .visible-mobile {\n"
                + "            display: block;\n"
                + "            }\n"
                + "            }\n"
                + "</style>\n"
                + "</head>\n"
                + "<body>\n"
                + "<table class=\"body\">\n"
                + "<tr>\n"
                + "	<td class=\"center\" align=\"center\" valign=\"top\">\n"
                + "		<!-- BEGIN: Header -->\n"
                + "		<table class=\"page-header\" align=\"center\">\n"
                + "		<tr>\n"
                + "			<td class=\"center\" align=\"center\">\n"
                + "				<!-- BEGIN: Header Container -->\n"
                + "				<table class=\"container\" align=\"center\">\n"
                + "				<tr>\n"
                + "					<td>\n"
                + "						<table class=\"row \">\n"
                + "						<tr>\n"
                + "							<td class=\"wrapper vertical-middle\">\n"
                + "								<!-- BEGIN: Logo -->\n"
                + "								<table class=\"six columns\">\n"
                + "								<tr>\n"
                + "									<td class=\"vertical-middle\">\n"
                + "										\n"
                + "										DeansList\n"
                + "										\n"
                + "									</td>\n"
                + "								</tr>\n"
                + "								</table>\n"
                + "								<!-- END: Logo -->\n"
                + "							</td>\n"
                + "							<td class=\"wrapper vertical-middle last\">\n"
                + "								<!-- BEGIN: Social Icons -->\n"
                + "								<table class=\"six columns\">\n"
                + "								<tr>\n"
                + "									<td>\n"
                + "									<!--	<table class=\"wrapper social-icons\" align=\"right\">\n"
                + "										<tr>\n"
                + "											<td class=\"vertical-middle\">\n"
                + "												<a href=\"#\">\n"
                + "												<img src=\"../../assets/admin/pages/media/email/social_facebook.png\" alt=\"social icon\"/>\n"
                + "												</a>\n"
                + "											</td>\n"
                + "											<td class=\"vertical-middle\">\n"
                + "												<a href=\"#\">\n"
                + "												<img src=\"../../assets/admin/pages/media/email/social_twitter.png\" alt=\"social icon\"/>\n"
                + "												</a>\n"
                + "											</td>\n"
                + "											<td class=\"vertical-middle\">\n"
                + "												<a href=\"#\">\n"
                + "												<img src=\"../../assets/admin/pages/media/email/social_googleplus.png\" alt=\"social icon\"/>\n"
                + "												</a>\n"
                + "											</td>\n"
                + "											<td class=\"vertical-middle\">\n"
                + "												<a href=\"#\">\n"
                + "												<img src=\"../../assets/admin/pages/media/email/social_linkedin.png\" alt=\"social icon\"/>\n"
                + "												</a>\n"
                + "											</td>\n"
                + "											<td class=\"vertical-middle\">\n"
                + "												<a href=\"#\">\n"
                + "												<img src=\"../../assets/admin/pages/media/email/social_rss.png\" alt=\"social icon\"/>\n"
                + "												</a>\n"
                + "											</td>\n"
                + "										</tr>\n"
                + "										</table>-->\n"
                + "									</td>\n"
                + "								</tr>\n"
                + "								</table>\n"
                + "								<!-- END: Social Icons -->\n"
                + "							</td>\n"
                + "						</tr>\n"
                + "						</table>\n"
                + "					</td>\n"
                + "				</tr>\n"
                + "				</table>\n"
                + "				<!-- END: Header Container -->\n"
                + "			</td>\n"
                + "		</tr>\n"
                + "		</table>\n"
                + "		<!-- END: Header -->\n"
                + "		<!-- BEGIN: Content -->\n"
                + "		<table class=\"container content\" align=\"center\">\n"
                + "		<tr>\n"
                + "			<td>\n"
                + "				<table class=\"row note\">\n"
                + "				<tr>\n"
                + "					<td class=\"wrapper last\">\n"
                + "						<h4>You are one step closer to being on the DeansList!</h4>\n"
                + "						<p>\n"
                + "							 Please click the following URL to activate your account:\n"
                + "						</p>\n"
                + "						<!-- BEGIN: Note Panel -->\n"
                + "						<table class=\"twelve columns\" style=\"margin-bottom: 10px\">\n"
                + "						<tr>\n"
                + "							<td class=\"panel\">\n"
                + "								<a href=\"http://localhost:8080/deanslist/verify_registration?" + link + "\">\n"
                + "								Verify DeansList account </a>\n"
                + "							</td>\n"
                + "							<td class=\"expander\">\n"
                + "							</td>\n"
                + "						</tr>\n"
                + "						</table>\n"
                + "						\n"
                + "						<!-- END: Note Panel -->\n"
                + "					</td>\n"
                + "				</tr>\n"
                + "				</table>\n"
                + "				<span class=\"devider\">\n"
                + "				</span>\n"
                + "				\n"
                + "			</td>\n"
                + "		</tr>\n"
                + "		</table>\n"
                + "		<!-- END: Content -->\n"
                + "		<!-- BEGIN: Footer -->\n"
                + "		<table class=\"page-footer\" align=\"center\">\n"
                + "		<tr>\n"
                + "			<td class=\"center\" align=\"center\">\n"
                + "				<table class=\"container\" align=\"center\">\n"
                + "				<tr>\n"
                + "					<td>\n"
                + "						<!-- BEGIN: Unsubscribet -->\n"
                + "						<table class=\"row\">\n"
                + "						<tr>\n"
                + "							<td class=\"wrapper last\">\n"
                + "								<span style=\"font-size:12px;\">\n"
                + "								<i>This ia a system generated email and reply is not required.</i>\n"
                + "								</span>\n"
                + "							</td>\n"
                + "						</tr>\n"
                + "						</table>\n"
                + "						<!-- END: Unsubscribe -->\n"
                + "						<!-- BEGIN: Footer Panel -->\n"
                + "						<table class=\"row\">\n"
                + "						<tr>\n"
                + "							<td class=\"wrapper\">\n"
                + "								<table class=\"four columns\">\n"
                + "								<tr>\n"
                + "									<td class=\"vertical-middle\">\n"
                + "										 &copy; DeansList 2014.\n"
                + "									</td>\n"
                + "								</tr>\n"
                + "								</table>\n"
                + "							</td>\n"
                + "							<td class=\"wrapper last\">\n"
                + "								<table class=\"eight columns\">\n"
                + "								<tr>\n"
                + "									<td class=\"vertical-middle align-reverse\">\n"
                + "										<a href=\"#\">\n"
                + "										About Us </a>\n"
                + "										&nbsp; <a href=\"#\">\n"
                + "										Privacy Policy </a>\n"
                + "										&nbsp; <a href=\"#\">\n"
                + "										Terms of Use </a>\n"
                + "									</td>\n"
                + "								</tr>\n"
                + "								</table>\n"
                + "							</td>\n"
                + "						</tr>\n"
                + "						</table>\n"
                + "						<!-- END: Footer Panel List -->\n"
                + "					</td>\n"
                + "				</tr>\n"
                + "				</table>\n"
                + "			</td>\n"
                + "		</tr>\n"
                + "		</table>\n"
                + "		<!-- END: Footer -->\n"
                + "	</td>\n"
                + "</tr>\n"
                + "</table>\n"
                + "</body>\n"
                + "</html>";
        return template;
    }
}
